version: 2
registries:
  # The registry is technically public, but GitHub
  # still requires authentication to access it.
  # https://github.com/orgs/community/discussions/23386#discussioncomment-3240193
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{ secrets.ACTION_PAT }}
updates:
  - package-ecosystem: "npm"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
    ignore:
      # Ignore storybook updates, as they require a migration script
      - dependency-name: "@storybook/*"
      - dependency-name: "storybook"
      - dependency-name: "eslint-plugin-storybook"
    registries:
      - npm-github
    groups:
      react:
        applies-to: version-updates
        patterns:
          - "react"
          - "react-dom"
      emotion:
        applies-to: version-updates
        patterns:
          - "@emotion/*"
      tolgee:
        applies-to: version-updates
        patterns:
          - "@tolgee/*"
      tanstack-router:
        applies-to: version-updates
        patterns:
          - "@tanstack/react-router"
          - "@tanstack/react-router-with-query"
  - package-ecosystem: "github-actions"
    rebase-strategy: auto
    open-pull-requests-limit: 25
    directory: "/"
    schedule:
      interval: daily
